global using Carter;
global using Marten;
global using Marten.Schema;
global using Marten.Pagination;
global using FluentValidation;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Mvc;
global using System.Diagnostics;
global using Scalar.AspNetCore;
global using Wolverine;
global using Wolverine.Marten;
global using Wolverine.FluentValidation;
global using Riok.Mapperly.Abstractions;
// global using Mapster;
// global using JasperFx;

global using Catalog.Api.Data.Seed;
global using Catalog.Api.Model;
global using Catalog.Api.CQRS;
global using Catalog.Api.Exceptions.Handler;
global using Catalog.Api.Exceptions;
global using Catalog.Api.Middleware;
global using Catalog.Api.Common;